#SPRING CONFIGURATION
spring:
  application:
    name: zuul-gateway

server:
  port: 8090

#EUREKA CONFIGURATION
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#ZUUL CONFIGURATION
zuul:
  routes:
    usuarios:
      serviceId: microservices-users
      path: /api/alumnos/v1/**
